### ISSUE TITLE
Finish adding WWT Web Control Objects

### ISSUE THREAD

**Issue by ojustino** [WorldWideTelescope/pywwt#39]
- [X] feature added to pywwt
- [ ] feature missing from pywwt
- [ ] ~~feature listed in docs but not available for use~~
_**questions and/or to-dos_

**Annotation Objects**
- [X] Annotation id Property (`Annotation` class in `annotation.py`)
- [X] Annotation label Property (`Annotation` class in `annotation.py`)
- [X] Annotation opacity Property (`Annotation` class in `annotation.py`)
- [X] Annotation showHoverLabel Property (`Annotation` class in `annotation.py`)
- [ ] Annotation center Property ("contains a Vector3d object for use by the web client")
- [X] Annotation tag Property (`Annotation` class in `annotation.py`)

**Circle Objects**
- [X] Circle Fill Property (trait of `Circle` class in `annotation.py`)
- [X] Circle FillColor Property (trait of `Circle` class in `annotation.py`) _**to be validated (PR #38)_
- [X] Circle LineColor Property (trait of `Circle` class in `annotation.py`) _**to be validated (PR #38)_
- [X] Circle LineWidth Property (trait of `Circle` class in `annotation.py`) _**to be validated (PR #38)_
- [X] Circle Radius Property (trait of `Circle` class in `annotation.py`) _**to be validated (PR #38)_
- [X] Circle SkyRelative Property (trait of `Circle` class in `annotation.py`)
- [X] Circle SetCenter Method (method of `Circle` class in `annotation.py`)

**Poly Objects**
- [X] Poly Fill Property (trait of `Poly` class in `annotation.py`)
- [X] Poly FillColor Property (trait of `Poly` class in `annotation.py`) _**to be validated (PR #38)_
- [X] Poly LineColor Property (trait of `Poly` class in `annotation.py`) _**to be validated (PR #38)_
- [X] Poly LineWidth Property (trait of `Poly` class in `annotation.py`) _**to be validated (PR #38)_
- [X] Poly AddPoint Method (method of `Poly` class in `annotation.py`)

**PolyLine Objects**
- [X] PolyLine LineColor Property (trait of `PolyLine` class in `annotation.py`) _**to be validated (PR #38)_
- [X] PolyLine LineWidth Property (trait of `PolyLine` class in `annotation.py`) _**to be validated (PR #38)_
- [X] PolyLine AddPoint Method (method of `PolyLine` class in `annotation.py`)

**Settings Objects**
- [X] Settings ConstellationBoundryColor Property (trait of `BaseWWTWidget` class in `core.py`) _**to be validated (PR #38)_
- [X] Settings ConstellationFigureColor Property (trait of `BaseWWTWidget` class in `core.py`) _**to be validated (PR #38)_
- [X] Settings ConstellationSelectionColor Property (trait of `BaseWWTWidget` class in `core.py`) _**to be validated (PR #38)_
- [ ] ~Settings EclipticColor Property~
- [ ] ~Settings GridColor Property~
- [X] Settings LocalHorizonMode Property (trait of `BaseWWTWidget` class in `core.py`)
- [X] Settings LocationAltitude Property (trait of `BaseWWTWidget` class in `core.py`) _**validated_
- [X] Settings LocationLat Property (trait of `BaseWWTWidget` class in `core.py`) _**validated_
- [X] Settings LocationLng Property (trait of `BaseWWTWidget` class in `core.py`) _**validated_
- [ ] ~Settings ShowClouds Property~
- [X] Settings ShowConstellationBoundries Property (trait of `BaseWWTWidget` class in `core.py`)
- [X] Settings ShowConstellationFigures Property (trait of `BaseWWTWidget` class in `core.py`)
- [X] Settings ShowConstellationSelection Property (trait of `BaseWWTWidget` class in `core.py`)
- [X] Settings ShowCrosshairs Property (trait of `BaseWWTWidget` class in `core.py`)
- [X] Settings ShowEcliptic Property (trait of `BaseWWTWidget` class in `core.py`)
- [ ] ~Settings ShowElevationModel Property~
- [ ] ~Settings ShowFieldOfView Property~
- [X] Settings ShowGrid Property (trait of `BaseWWTWidget` class in `core.py`)
- [ ] ~Settings ShowHorizon Property~
- [ ] ~Settings ShowHorizonPanorama Property~
- [ ] ~Settings ShowMoonsAsPointSource Property~
- [ ] ~Settings ShowSolarSystem Property~
- [ ] ~Settings ShowUTCTime Property~
- [ ] ~Settings SolarSystemCosmos Property~
- [ ] ~Settings SolarSystemLighting Property~
- [ ] ~Settings SolarSystemMilkyWay Property~
- [ ] ~Settings SolarSystemMultiRes Property~
- [ ] ~Settings SolarSystemOrbitColor Property~
- [ ] ~Settings SolarSystemOrbits Property~
- [ ] ~Settings SolarSystemOverlays Property~
- [ ] ~Settings SolarSystemScale Property~
- [ ] ~Settings SolarSystemStars Property~
- [ ] ~Settings UserID Property~

**WWTControl Objects**
- [ ] ~WWTControl Fov Property~
- [ ] WWTControl Settings Property ("references the Settings object for WWTControl") _**(Is this one necessary? The user can type `wwt.setting` and see that setting's current value.)_
- [ ] ~WWTControl SmoothAnimation Property~
- [X] WWTControl AddAnnotation Method (bundled into Create methods below)
- [ ] WWTControl ClearAnnotations Method (PR #33)
- [X] WWTControl CreateCircle Method (`Annotation` class in `annotation.py`)
- [X] WWTControl CreatePolygon Method (`Annotation` class in `annotation.py`)
- [X] WWTControl CreatePolyLine Method (`Annotation` class in `annotation.py`)
- [ ] WWTControl GetDec Method (PR #33)
- [ ] WWTControl GetRA Method (PR #33)
- [X] WWTControl GotoRaDecZoom Method (`center_on_coordinates` method of `Annotation` class in `annotation.py`)
- [ ] ~WWTControl HideUI Method~
- [X] WWTControl LoadImageCollection Method (method of `Annotation` class in `annotation.py`)
- [X] WWTControl LoadTour Method (method of `Annotation` class in `annotation.py`)
- [ ] ~WWTControl LoadVOTable Method~
- [X] WWTControl PlayTour Method (method of `Annotation` class in `annotation.py`)
- [ ] WWTControl RemoveAnnotation Method (PR #33)
- [X] WWTControl SetBackgroundImageByName Method (trait of `BaseWWTWidget` class in `core.py`) _**to be validated???_
- [X] WWTControl SetForegroundImageByName Method (trait of `BaseWWTWidget` class in `core.py`) _**to be validated???_
- [X] WWTControl SetForegroundOpacity Method _**(This one is said to be unavailable, though you wrote code for it. I haven't tried loading an image yet, but I'll see if it works on my end, too.)_
- [X] WWTControl StopTour Method (method of `Annotation` class in `annotation.py`)
- [ ] WWTControl AnnotationClicked Event ("fired when an Annotation object is clicked")
- [ ] WWTControl Arrived Event ("fired when a change to the view from a drag, zoom, or gotoRaDecZoom comes to a halt")
- [ ] WWTControl Click Event ("fired when the left mouse button is clicked")
- [ ] WWTControl Ready Event ("fired when the web client is initialized")
